### ISSUE TITLE
Prior art

### ISSUE THREAD

**Issue by gudovskiy** [lzx1413/CAFFE_SSD#1]
Hi, how is your idea different than [https://arxiv.org/pdf/1704.05776.pdf](https://arxiv.org/pdf/1704.05776.pdf) or [https://arxiv.org/pdf/1704.05776.pdf](https://arxiv.org/pdf/1704.05776.pdf) ?

**Comment by lzx1413** [comment]
The paper you mentioned is more similar with the RSSD which is cited in my paper. The difference between us is the way to fuse the features.
