### ISSUE TITLE
F-SSD Framwork

### ISSUE THREAD

**Issue by TrungHieu-Le** [lzx1413/CAFFE_SSD#5]
Hello lzx1413,
In figure 2 of F-SSD paper, Could you please let me know
1. How can FC_7 and Con7_2 be interpolated to 38x38?
2. You concatenated 3 layers (38x38x256), apter BatchNorm, why the dimension is 38x38x512?
Thank you.

**Comment by lzx1413** [comment]
1. we use bilinear interp  to expand the feature size to 38*38.
2. There we add a convolution to reduce the dimension to  512.

**Comment by TrungHieu-Le** [comment]
I understood, 
Thank you!
